=== crystal-rangel/729summer2023/book-clr-v01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:clr="https://crystalrangel.000webhostapp.com/729/metadata" targetNamespace="https://crystalrangel.000webhostapp.com/729/metadata" xmlns:mods="http://www.loc.gov/mods/v3" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
       An XML schema for book with qualified DC metadata
       For v01, the metadata only allows DC, now it also allows MODS
       Replaced kbng with clr.
     </xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="qualifieddc.xsd"/>
	<xsd:import namespace="http://www.loc.gov/mods/v3" schemaLocation="mods-3-7.xsd"/>
	<xsd:element name="shortstory" type="clr:shortstoryType"/>
	<xsd:complexType name="shortstoryType">
		<xsd:sequence>
			<xsd:element ref="clr:metadata"/>
			<xsd:element ref="clr:maintext"/>
		</xsd:sequence>
		<xsd:attribute name="FileID" type="xsd:ID" use="required"/>
	</xsd:complexType>
	<xsd:element name="metadata">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="clr:qualifieddc"/>
				<xsd:element ref="mods:mods"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="maintext">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="paragraph" type="clr:paragraphType"/>
				<xsd:element ref="clr:speech"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="paragraphType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="clr:speech" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="speech" type="xsd:string"/>
</xsd:schema>

=== crystal-rangel/729summer2023/Jackson.TheLottery.Assignment7.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="shortstory01.xsl"?>
<clr:shortstory
  xmlns:clr="https://crystalrangel.000webhostapp.com/729/metadata"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://crystalrangel.000webhostapp.com/729/metadata book-clr-v01.xsd"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:dcmitype="http://purl.org/dc/dcmitype/" 
  FileID="SS-SJ-TL-01">

<clr:metadata>
	<clr:qualifieddc>
	<dc:title>The lottery</dc:title>
		<dc:creator>Jackson, Shirley 1916-1965</dc:creator>
		<dc:type xsi:type="dcterms:DCMIType">Text</dc:type>
		<dcterms:available xsi:type="dcterms:W3CDTF">2008</dcterms:available>
		<dc:description>
			Shirley Jackson's classic The Lottery portrays a small town that gathers to hold its yearly lottery, a barbaric game of chance. Each head of household draws a slip, and the family with the marked slip will lose a member to stoning by the townsfolk.
		</dc:description>
		<dc:format>25 kb</dc:format>
		<dc:identifier>https://purl.archive.org/net/729summer/crangel/lottery/text</dc:identifier> 
		<dc:identifier>https://crystalrangel.000webhostapp.com/729/Jackson.TheLottery.Assignment7.xml</dc:identifier>
		<dc:source>St. Louis Public Schools, https://www.slps.org/cms/lib/MO01001157/Centricity/Domain/10749/The_Lottery.pdf</dc:source>
		<dc:language xsi:type="dcterms:ISO639-2">eng </dc:language>
		<dc:relation>Assignment 7 for K.B.Ng's GSLIS 729</dc:relation>
		<dc:rights>
			The only legal and authorized use of these files is for the nonprofit production. The copyright for these files is the sole property of the original owner.  
		</dc:rights>
		<dcterms:accessRights>Access limited to students of GSLIS 729</dcterms:accessRights>
		<dc:subject xsi:type="dcterms:LCSH">Rituals and ceremonies. Fiction.</dc:subject> 
		<dc:subject xsi:type="dcterms:LCC">PS3519.A392</dc:subject>
		<dc:subject xsi:type="dcterms:LCSH">Horror tales, American. 20th century</dc:subject> 
		<dc:subject xsi:type="dcterms:LCSH">Short stories, American. 20th century</dc:subject>
	</clr:qualifieddc>
</clr:metadata>

<clr:maintext>
<clr:paragraph>The morning of June 27th was clear and sunny, with the fresh warmth of a full-summer day; the flowers
were blossoming profusely and the grass was richly green. The people of the village began to gather in
the square, between the post office and the bank, around ten o'clock; in some towns there were so many
people that the lottery took two days and had to be started on June 2th. but in this village, where there
were only about three hundred people, the whole lottery took less than two hours, so it could begin at ten
o'clock in the morning and still be through in time to allow the villagers to get home for noon dinner.</clr:paragraph>

<clr:paragraph>The children assembled first, of course. School was recently over for the summer, and the feeling of
liberty sat uneasily on most of them; they tended to gather together quietly for a while before they broke
into boisterous play. and their talk was still of the classroom and the teacher, of books and reprimands.
Bobby Martin had already stuffed his pockets full of stones, and the other boys soon followed his
example, selecting the smoothest and roundest stones; Bobby and Harry Jones and Dickie Delacroix-- the
villagers pronounced this name "Dellacroy"--eventually made a great pile of stones in one corner of the
square and guarded it against the raids of the other boys. The girls stood aside, talking among themselves,
looking over their shoulders at rolled in the dust or clung to the hands of their older brothers or sisters.</clr:paragraph>

<clr:paragraph>Soon the men began to gather. surveying their own children, speaking of planting and rain, tractors and
taxes. They stood together, away from the pile of stones in the corner, and their jokes were quiet and they
smiled rather than laughed. The women, wearing faded house dresses and sweaters, came shortly after
their menfolk. They greeted one another and exchanged bits of gossip as they went to join their husbands.
Soon the women, standing by their husbands, began to call to their children, and the children came
reluctantly, having to be called four or five times. Bobby Martin ducked under his mother's grasping hand
and ran, laughing, back to the pile of stones. His father spoke up sharply, and Bobby came quickly and
took his place between his father and his oldest brother.</clr:paragraph>

<clr:paragraph>The lottery was conducted--as were the square dances, the teen club, the Halloween program--by Mr.
Summers. who had time and energy to devote to civic activities. He was a round-faced, jovial man and he
ran the coal business, and people were sorry for him. because he had no children and his wife was a
scold. When he arrived in the square, carrying the black wooden box, there was a murmur of
conversation among the villagers, and he waved and called. <clr:speech>"Little late today, folks."</clr:speech> The postmaster, Mr.
Graves, followed him, carrying a three- legged stool, and the stool was put in the center of the square and
Mr. Summers set the black box down on it. The villagers kept their distance, leaving a space between
themselves and the stool. and when Mr. Summers said, <clr:speech>"Some of you fellows want to give me a hand?"</clr:speech>
there was a hesitation before two men. Mr. Martin and his oldest son, Baxter. came forward to hold the
box steady on the stool while Mr. Summers stirred up the papers inside it.</clr:paragraph>

<clr:paragraph>The original paraphernalia for the lottery had been lost long ago, and the black box now resting on the
stool had been put into use even before Old Man Warner, the oldest man in town, was born. Mr.
Summers spoke frequently to the villagers about making a new box, but no one liked to upset even as
much tradition as was represented by the black box. There was a story that the present box had been
made with some pieces of the box that had preceded it, the one that had been constructed when the first
people settled down to make a village here. Every year, after the lottery, Mr. Summers began talking
again about a new box, but every year the subject was allowed to fade off without anything's being done.
The black box grew shabbier each year: by now it was no longer completely black but splintered badly
along one side to show the original wood color, and in some places faded or stained.</clr:paragraph>

<clr:paragraph>Mr. Martin and his oldest son, Baxter, held the black box securely on the stool until Mr. Summers had
stirred the papers thoroughly with his hand. Because so much of the ritual had been forgotten or
discarded, Mr. Summers had been successful in having slips of paper substituted for the chips of wood
that had been used for generations. Chips of wood, Mr. Summers had argued. had been all very well
when the village was tiny, but now that the population was more than three hundred and likely to keep on
growing, it was necessary to use something that would fit more easily into he black box. The night before
the lottery, Mr. Summers and Mr. Graves made up the slips of paper and put them in the box, and it was
then taken to the safe of Mr. Summers' coal company and locked up until Mr. Summers was ready to take
it to the square next morning. The rest of the year, the box was put way, sometimes one place, sometimes
another; it had spent one year in Mr. Graves's barn and another year underfoot in the post office. and
sometimes it was set on a shelf in the Martin grocery and left there.</clr:paragraph>

<clr:paragraph>There was a great deal of fussing to be done before Mr. Summers declared the lottery open. There were
the lists to make up--of heads of families. heads of households in each family. members of each
household in each family. There was the proper swearing-in of Mr. Summers by the postmaster, as the
official of the lottery; at one time, some people remembered, there had been a recital of some sort,
performed by the official of the lottery, a perfunctory. tuneless chant that had been rattled off duly each
year; some people believed that the official of the lottery used to stand just so when he said or sang it,
others believed that he was supposed to walk among the people, but years and years ago this part of the
ritual had been allowed to lapse. There had been, also, a ritual salute, which the official of the lottery had
had to use in addressing each person who came up to draw from the box, but this also had changed with
time, until now it was felt necessary only for the official to speak to each person approaching. Mr.
Summers was very good at all this; in his clean white shirt and blue jeans. with one hand resting
carelessly on the black box. he seemed very proper and important as he talked interminably to Mr. Graves
and the Martins.</clr:paragraph>

<clr:paragraph>Just as Mr. Summers finally left off talking and turned to the assembled villagers, Mrs. Hutchinson came
hurriedly along the path to the square, her sweater thrown over her shoulders, and slid into place in the
back of the crowd. <clr:speech>"Clean forgot what day it was,"</clr:speech> she said to Mrs. Delacroix, who stood next to her, and
they both laughed softly. <clr:speech>"Thought my old man was out back stacking wood,"</clr:speech> Mrs. Hutchinson went on.
<clr:speech>"and then I looked out the window and the kids was gone, and then I remembered it was the twenty-
seventh and came a-running."</clr:speech> She dried her hands on her apron, and Mrs. Delacroix said, <clr:speech>"You're in time,
though. They're still talking away up there."</clr:speech></clr:paragraph>

<clr:paragraph>Mrs. Hutchinson craned her neck to see through the crowd and found her husband and children standing
near the front. She tapped Mrs. Delacroix on the arm as a farewell and began to make her way through
